<?php

$GLOBALS['fw_fields']['common']['elements']['background'] = array (
	'settings' => array (
		'title' => 'Element — Background'
	),
	'field_group' => array (
		'key' => 'builder_element_bg',
		'title' => 'Background',
		'fields' => array(
			array(
				'key' => 'builder_element_bg_type',
				'label' => 'Background Type',
				'name' => 'type',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'image' => 'Image',
					'video' => 'Video',
					'thumbnail' => 'Post Thumbnail',
				),
				'default_value' => false,
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'builder_element_bg_colour',
				'label' => 'Background Colour',
				'name' => 'colour',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '33',
					'class' => '',
					'id' => '',
				),
				'choices' => array_merge ( array ( 'inherit' => 'Inherited from Parent' ), $GLOBALS['defaults']['theme_colours'] ),
				'default_value' => false,
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'builder_element_bg_image',
				'label' => 'Image',
				'name' => 'image',
				'type' => 'image',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'builder_element_bg_type',
							'operator' => '==',
							'value' => 'image',
						),
					),
					array(
						array(
							'field' => 'builder_element_bg_type',
							'operator' => '==',
							'value' => 'video',
						),
					),
				),
				'wrapper' => array(
					'width' => '33',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'id',
				'preview_size' => 'thumbnail',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
			),
			array(
				'key' => 'builder_element_bg_video',
				'label' => 'Video',
				'name' => 'video',
				'type' => 'file',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'builder_element_bg_type',
							'operator' => '==',
							'value' => 'video',
						),
					),
				),
				'wrapper' => array(
					'width' => '33',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'id',
				'library' => 'all',
				'min_size' => '',
				'max_size' => '',
				'mime_types' => '',
			),
			array(
				'key' => 'builder_element_bg_opacity',
				'label' => 'Background Opacity',
				'name' => 'opacity',
				'type' => 'range',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '33',
					'class' => '',
					'id' => '',
				),
				'default_value' => 100,
				'min' => 0,
				'max' => 100,
				'step' => 10,
				'prepend' => '',
				'append' => '%',
			),
			array(
				'key' => 'builder_element_bg_position',
				'label' => 'Background Position',
				'name' => 'position',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'builder_element_bg_type',
							'operator' => '!=empty',
						),
						array(
							'field' => 'builder_element_bg_type',
							'operator' => '!=',
							'value' => 'video',
						),
					),
				),
				'wrapper' => array(
					'width' => '33',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'top left' => 'Top Left',
					'top center' => 'Top Center',
					'top right' => 'Top Right',
					'center left' => 'Center Left',
					'center center' => 'Center',
					'center right' => 'Center Right',
					'bottom left' => 'Bottom Left',
					'bottom center' => 'Bottom Center',
					'bottom right' => 'Bottom Right',
				),
				'default_value' => 'center center',
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'builder_element_bg_attachment',
				'label' => 'Background Attachment',
				'name' => 'attachment',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'builder_element_bg_type',
							'operator' => '!=empty',
						),
						array(
							'field' => 'builder_element_bg_type',
							'operator' => '!=',
							'value' => 'video',
						),
					),
				),
				'wrapper' => array(
					'width' => '33',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'scroll' => 'Scroll',
					'fixed' => 'Fixed',
				),
				'default_value' => 'scroll',
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'builder_element_bg_size',
				'label' => 'Background Size',
				'name' => 'size',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'builder_element_bg_type',
							'operator' => '!=empty',
						),
						array(
							'field' => 'builder_element_bg_type',
							'operator' => '!=',
							'value' => 'video',
						),
					),
				),
				'wrapper' => array(
					'width' => '33',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'cover' => 'Cover',
					'width' => '100% width, auto height',
					'height' => '100% height, auto width',
				),
				'default_value' => 'cover',
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
		),
		'active' => false,
	)
);

$GLOBALS['fw_fields']['common']['elements']['button'] = array(
	'settings' => array (
		'title' => 'Element — Button'
	),
	'field_group' => array (
		'key' => 'builder_element_button',
		'title' => 'Button',
		'fields' => array(
			array(
				'key' => 'builder_element_button_text',
				'label' => 'Button Text',
				'name' => 'text',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'builder_element_button_link_type',
							'operator' => '!=',
							'value' => 'next',
						),
					),
				),
				'wrapper' => array(
					'width' => '30',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'builder_element_button_link_type',
				'label' => 'Link Type',
				'name' => 'type',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '30',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'scroll' => 'Scroll to section',
					'post' => 'Post',
					'page' => 'Page',
					'url' => 'URL',
				),
				'default_value' => false,
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'builder_element_button_link_id',
				'label' => 'Section ID',
				'name' => 'id',
				'type' => 'text',
				'instructions' => 'Leave blank to scroll to the next section',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'builder_element_button_link_type',
							'operator' => '==',
							'value' => 'scroll',
						),
					),
				),
				'wrapper' => array(
					'width' => '40',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '#',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'builder_element_button_link_post',
				'label' => 'Post',
				'name' => 'post',
				'type' => 'post_object',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'builder_element_button_link_type',
							'operator' => '==',
							'value' => 'post',
						),
					),
				),
				'wrapper' => array(
					'width' => '40',
					'class' => '',
					'id' => '',
				),
				'wpml_cf_preferences' => 0,
				'post_type' => array(
					0 => 'post',
				),
				'taxonomy' => '',
				'allow_null' => 0,
				'multiple' => 0,
				'return_format' => 'id',
				'ui' => 1,
			),
			array(
				'key' => 'builder_element_button_link_page',
				'label' => 'Page',
				'name' => 'page',
				'type' => 'post_object',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'builder_element_button_link_type',
							'operator' => '==',
							'value' => 'page',
						),
					),
				),
				'wrapper' => array(
					'width' => '40',
					'class' => '',
					'id' => '',
				),
				'post_type' => array(
					0 => 'page',
				),
				'taxonomy' => '',
				'allow_null' => 0,
				'multiple' => 0,
				'return_format' => 'id',
				'ui' => 1,
			),
			array(
				'key' => 'builder_element_button_link_url',
				'label' => 'URL',
				'name' => 'url',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'builder_element_button_link_type',
							'operator' => '==',
							'value' => 'url',
						),
					),
				),
				'wrapper' => array(
					'width' => '40',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'builder_element_button_id',
				'label' => 'Button ID',
				'name' => 'button_id',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '30',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '#',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'builder_element_button_classes',
				'label' => 'Additional CSS Classes',
				'name' => 'classes',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '30',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'builder_element_button_link_target',
				'label' => 'Link Target',
				'name' => 'target',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '40',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'default' => 'Same window',
					'_blank' => 'New window',
				),
				'default_value' => false,
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'builder_element_button_icon',
				'label' => 'Icon',
				'name' => 'icon',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'builder_element_button_icon_placement',
						'label' => 'Placement',
						'name' => 'placement',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'none' => 'No icon',
							'before' => 'Before text',
							'after' => 'After text',
						),
						'default_value' => 'none',
						'allow_null' => 0,
						'multiple' => 0,
						'ui' => 0,
						'return_format' => 'value',
						'ajax' => 0,
						'placeholder' => '',
					),
					array(
						'key' => 'builder_element_button_icon_class',
						'label' => 'Icon Class',
						'name' => 'icon',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'builder_element_button_icon_placement',
									'operator' => '!=',
									'value' => 'none',
								),
							),
						),
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
				),
			),
			array(
				'key' => 'builder_element_button_colours',
				'label' => 'Colours',
				'name' => 'colours',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'builder_element_button_colours_bg',
						'label' => 'Background',
						'name' => 'btn_bg',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '33',
							'class' => '',
							'id' => '',
						),
						'choices' => array_merge ( array ( 'inherit' => 'Inherited from Parent' ), $GLOBALS['defaults']['theme_colours'] ),
						'default_value' => false,
						'allow_null' => 0,
						'multiple' => 0,
						'ui' => 0,
						'return_format' => 'value',
						'ajax' => 0,
						'placeholder' => '',
					),
					array(
						'key' => 'builder_element_button_colours_text',
						'label' => 'Text',
						'name' => 'btn_text',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '33',
							'class' => '',
							'id' => '',
						),
						'choices' => array_merge ( array ( 'inherit' => 'Inherited from Parent' ), $GLOBALS['defaults']['theme_colours'] ),
						'default_value' => false,
						'allow_null' => 0,
						'multiple' => 0,
						'ui' => 0,
						'return_format' => 'value',
						'ajax' => 0,
						'placeholder' => '',
					),
					array(
						'key' => 'builder_element_button_colours_border',
						'label' => 'Border',
						'name' => 'btn_border',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '33',
							'class' => '',
							'id' => '',
						),
						'choices' => array_merge ( array ( 'inherit' => 'Inherited from Parent' ), $GLOBALS['defaults']['theme_colours'] ),
						'default_value' => false,
						'allow_null' => 0,
						'multiple' => 0,
						'ui' => 0,
						'return_format' => 'value',
						'ajax' => 0,
						'placeholder' => '',
					),
				),
			),
		),
		'active' => false,
	)
);

$GLOBALS['fw_fields']['common']['elements']['colours'] = array(
	'settings' => array (
		'title' => 'Element — Colours'
	),
	'field_group' => array (
		'key' => 'builder_element_colours',
		'title' => 'Colours',
		'fields' => array(
			array(
				'key' => 'builder_element_colours_heading',
				'label' => 'Heading',
				'name' => 'heading_colour',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '33',
					'class' => '',
					'id' => '',
				),
				'choices' => array_merge ( array ( 'inherit' => 'Inherited from Parent' ), $GLOBALS['defaults']['theme_colours'] ),
				'default_value' => false,
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'builder_element_colours_text',
				'label' => 'Text',
				'name' => 'text_colour',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '33',
					'class' => '',
					'id' => '',
				),
				'choices' => array_merge ( array ( 'inherit' => 'Inherited from Parent' ), $GLOBALS['defaults']['theme_colours'] ),
				'default_value' => false,
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'builder_element_colours_link',
				'label' => 'Link',
				'name' => 'link_colour',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '33',
					'class' => '',
					'id' => '',
				),
				'choices' => array_merge ( array ( 'inherit' => 'Inherited from Parent' ), $GLOBALS['defaults']['theme_colours'] ),
				'default_value' => false,
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
		),
		'active' => false,
	)
);

$GLOBALS['fw_fields']['common']['elements']['search'] = array(
	'settings' => array (
		'title' => 'Element — Search Form'
	),
	'field_group' => array (
		'key' => 'builder_element_search',
		'title' => 'Search Form',
		'fields' => array(
			array(
				'key' => 'builder_element_search_text_placeholder',
				'label' => 'Text Field — Placeholder',
				'name' => 'text_placeholder',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => 'Search',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'builder_element_search_text_class',
				'label' => 'Text Field — Class',
				'name' => 'text_class',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'builder_element_search_button_icon',
				'label' => 'Button — Icon',
				'name' => 'btn_icon',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'builder_element_search_button_class',
				'label' => 'Button — Class',
				'name' => 'btn_class',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
		),
		'active' => false,
	)
);
