<?php

$GLOBALS['fw_fields']['common']['function']['breakpoints'] = array(
	'settings' => array (
		'title' => 'Function — Breakpoints'
	),
	'field_group' => array (
		'key' => 'builder_function_breakpoints',
		'title' => 'Breakpoints',
		'fields' => array(
			array(
				'key' => 'field_5d07df1140b4a',
				'label' => 'Breakpoints',
				'name' => 'breakpoints',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => 'col-breakpoints hide-label',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_5d07df1c40b4b',
						'label' => 'Default',
						'name' => 'xs',
						'type' => 'group',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'layout' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_5d07e72d8e974',
								'label' => 'Hide',
								'name' => 'hide',
								'type' => 'true_false',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '16',
									'class' => '',
									'id' => '',
								),
								'message' => 'Hide',
								'default_value' => 0,
								'ui' => 0,
								'ui_on_text' => '',
								'ui_off_text' => '',
							),
							array(
								'key' => 'field_5d07df7540b4d',
								'label' => 'Columns',
								'name' => 'col',
								'type' => 'number',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => array(
									array(
										array(
											'field' => 'field_5d07e72d8e974',
											'operator' => '!=',
											'value' => '1',
										),
									),
								),
								'wrapper' => array(
									'width' => '28',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => 'col-',
								'append' => '',
								'min' => 1,
								'max' => 12,
								'step' => 1,
							),
							array(
								'key' => 'field_5d07df8740b4e',
								'label' => 'Offset',
								'name' => 'offset',
								'type' => 'number',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => array(
									array(
										array(
											'field' => 'field_5d07e72d8e974',
											'operator' => '!=',
											'value' => '1',
										),
									),
								),
								'wrapper' => array(
									'width' => '28',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => 'offset-',
								'append' => '',
								'min' => 0,
								'max' => 11,
								'step' => 1,
							),
							array(
								'key' => 'field_5d07df9b40b4f',
								'label' => 'Order',
								'name' => 'order',
								'type' => 'number',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => array(
									array(
										array(
											'field' => 'field_5d07e72d8e974',
											'operator' => '!=',
											'value' => '1',
										),
									),
								),
								'wrapper' => array(
									'width' => '28',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => 'order-',
								'append' => '',
								'min' => 0,
								'max' => 12,
								'step' => 1,
							),
						),
					),
					array(
						'key' => 'field_5d07e841be02e',
						'label' => 'Small',
						'name' => 'sm',
						'type' => 'group',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'layout' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_5d07e841be02f',
								'label' => 'Hide',
								'name' => 'hide',
								'type' => 'true_false',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '16',
									'class' => '',
									'id' => '',
								),
								'message' => 'Hide',
								'default_value' => 0,
								'ui' => 0,
								'ui_on_text' => '',
								'ui_off_text' => '',
							),
							array(
								'key' => 'field_5d07e841be030',
								'label' => 'Columns',
								'name' => 'col',
								'type' => 'number',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => array(
									array(
										array(
											'field' => 'field_5d07e841be02f',
											'operator' => '!=',
											'value' => '1',
										),
									),
								),
								'wrapper' => array(
									'width' => '28',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => 'col-sm-',
								'append' => '',
								'min' => 1,
								'max' => 12,
								'step' => 1,
							),
							array(
								'key' => 'field_5d07e841be031',
								'label' => 'Offset',
								'name' => 'offset',
								'type' => 'number',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => array(
									array(
										array(
											'field' => 'field_5d07e841be02f',
											'operator' => '!=',
											'value' => '1',
										),
									),
								),
								'wrapper' => array(
									'width' => '28',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => 'offset-sm-',
								'append' => '',
								'min' => 0,
								'max' => 11,
								'step' => 1,
							),
							array(
								'key' => 'field_5d07e841be032',
								'label' => 'Order',
								'name' => 'order',
								'type' => 'number',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => array(
									array(
										array(
											'field' => 'field_5d07e841be02f',
											'operator' => '!=',
											'value' => '1',
										),
									),
								),
								'wrapper' => array(
									'width' => '28',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => 'order-sm-',
								'append' => '',
								'min' => 0,
								'max' => 12,
								'step' => 1,
							),
						),
					),
					array(
						'key' => 'field_5d07e847be033',
						'label' => 'Medium',
						'name' => 'md',
						'type' => 'group',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'layout' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_5d07e847be034',
								'label' => 'Hide',
								'name' => 'hide',
								'type' => 'true_false',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '16',
									'class' => '',
									'id' => '',
								),
								'message' => 'Hide',
								'default_value' => 0,
								'ui' => 0,
								'ui_on_text' => '',
								'ui_off_text' => '',
							),
							array(
								'key' => 'field_5d07e847be035',
								'label' => 'Columns',
								'name' => 'col',
								'type' => 'number',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => array(
									array(
										array(
											'field' => 'field_5d07e847be034',
											'operator' => '!=',
											'value' => '1',
										),
									),
								),
								'wrapper' => array(
									'width' => '28',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => 'col-md-',
								'append' => '',
								'min' => 1,
								'max' => 12,
								'step' => 1,
							),
							array(
								'key' => 'field_5d07e847be036',
								'label' => 'Offset',
								'name' => 'offset',
								'type' => 'number',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => array(
									array(
										array(
											'field' => 'field_5d07e847be034',
											'operator' => '!=',
											'value' => '1',
										),
									),
								),
								'wrapper' => array(
									'width' => '28',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => 'offset-md-',
								'append' => '',
								'min' => 0,
								'max' => 11,
								'step' => 1,
							),
							array(
								'key' => 'field_5d07e847be037',
								'label' => 'Order',
								'name' => 'order',
								'type' => 'number',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => array(
									array(
										array(
											'field' => 'field_5d07e847be034',
											'operator' => '!=',
											'value' => '1',
										),
									),
								),
								'wrapper' => array(
									'width' => '28',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => 'order-md-',
								'append' => '',
								'min' => 0,
								'max' => 12,
								'step' => 1,
							),
						),
					),
					array(
						'key' => 'field_5d07e84cbe038',
						'label' => 'Large',
						'name' => 'lg',
						'type' => 'group',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'layout' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_5d07e84cbe039',
								'label' => 'Hide',
								'name' => 'hide',
								'type' => 'true_false',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '16',
									'class' => '',
									'id' => '',
								),
								'message' => 'Hide',
								'default_value' => 0,
								'ui' => 0,
								'ui_on_text' => '',
								'ui_off_text' => '',
							),
							array(
								'key' => 'field_5d07e84cbe03a',
								'label' => 'Columns',
								'name' => 'col',
								'type' => 'number',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => array(
									array(
										array(
											'field' => 'field_5d07e84cbe039',
											'operator' => '!=',
											'value' => '1',
										),
									),
								),
								'wrapper' => array(
									'width' => '28',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => 'col-lg-',
								'append' => '',
								'min' => 1,
								'max' => 12,
								'step' => 1,
							),
							array(
								'key' => 'field_5d07e84cbe03b',
								'label' => 'Offset',
								'name' => 'offset',
								'type' => 'number',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => array(
									array(
										array(
											'field' => 'field_5d07e84cbe039',
											'operator' => '!=',
											'value' => '1',
										),
									),
								),
								'wrapper' => array(
									'width' => '28',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => 'offset-lg-',
								'append' => '',
								'min' => 0,
								'max' => 11,
								'step' => 1,
							),
							array(
								'key' => 'field_5d07e84cbe03c',
								'label' => 'Order',
								'name' => 'order',
								'type' => 'number',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => array(
									array(
										array(
											'field' => 'field_5d07e84cbe039',
											'operator' => '!=',
											'value' => '1',
										),
									),
								),
								'wrapper' => array(
									'width' => '28',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => 'order-lg-',
								'append' => '',
								'min' => 0,
								'max' => 12,
								'step' => 1,
							),
						),
					),
					array(
						'key' => 'field_5d07e852be03d',
						'label' => 'X-Large',
						'name' => 'xl',
						'type' => 'group',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'layout' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_5d07e852be03e',
								'label' => 'Hide',
								'name' => 'hide',
								'type' => 'true_false',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '16',
									'class' => '',
									'id' => '',
								),
								'message' => 'Hide',
								'default_value' => 0,
								'ui' => 0,
								'ui_on_text' => '',
								'ui_off_text' => '',
							),
							array(
								'key' => 'field_5d07e852be03f',
								'label' => 'Columns',
								'name' => 'col',
								'type' => 'number',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => array(
									array(
										array(
											'field' => 'field_5d07e852be03e',
											'operator' => '!=',
											'value' => '1',
										),
									),
								),
								'wrapper' => array(
									'width' => '28',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => 'col-xl-',
								'append' => '',
								'min' => 1,
								'max' => 12,
								'step' => 1,
							),
							array(
								'key' => 'field_5d07e852be040',
								'label' => 'Offset',
								'name' => 'offset',
								'type' => 'number',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => array(
									array(
										array(
											'field' => 'field_5d07e852be03e',
											'operator' => '!=',
											'value' => '1',
										),
									),
								),
								'wrapper' => array(
									'width' => '28',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => 'offset-xl-',
								'append' => '',
								'min' => 0,
								'max' => 11,
								'step' => 1,
							),
							array(
								'key' => 'field_5d07e852be041',
								'label' => 'Order',
								'name' => 'order',
								'type' => 'number',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => array(
									array(
										array(
											'field' => 'field_5d07e852be03e',
											'operator' => '!=',
											'value' => '1',
										),
									),
								),
								'wrapper' => array(
									'width' => '28',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => 'order-xl-',
								'append' => '',
								'min' => 0,
								'max' => 12,
								'step' => 1,
							),
						),
					),
				),
			),
		),
		'active' => false,
	)
);

//
// QUERY
//

// create an array of post types

$query_selectable_types = array();

if ( !empty ( get_post_types ( array ( 'publicly_queryable' => true ) ) ) ) {
	
	$query_selectable_types = get_post_types ( array ( 'publicly_queryable' => true ) );
	
	$query_selectable_types['page'] = 'page';

}

$GLOBALS['fw_fields']['common']['function']['query'] = array(
	'settings' => array (
		'title' => 'Function — Query'
	),
	'field_group' => array (
		'key' => 'builder_function_query',
		'title' => 'Query',
		'fields' => array(
			array(
				'key' => 'field_5bbcff04bef32',
				'label' => 'Number of Items',
				'name' => 'posts_per_page',
				'type' => 'number',
				'instructions' => 'How many items to retrieve. Enter -1 to get all items.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '40',
					'class' => '',
					'id' => '',
				),
				'default_value' => -1,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => -1,
				'max' => 20,
				'step' => 1,
			),
			array(
				'key' => 'field_5bb3bbb6d5893',
				'label' => 'Query Type',
				'name' => 'query_type',
				'type' => 'select',
				'instructions' => 'Retrieve posts or terms?',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '40',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'posts' => 'Posts',
					'terms' => 'Taxonomy Terms',
				),
				'default_value' => false,
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_5e94742af8f17',
				'label' => 'Debug',
				'name' => 'debug',
				'type' => 'true_false',
				'instructions' => 'Output debug info',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '20',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 1,
				'ui_on_text' => 'On',
				'ui_off_text' => 'Off',
			),
			array(
				'key' => 'field_5c548e7083376',
				'label' => 'Post Parameters',
				'name' => 'post',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5bb3bbb6d5893',
							'operator' => '==',
							'value' => 'posts',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_5c54931652f7b',
						'label' => 'Basic',
						'name' => '',
						'type' => 'tab',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'placement' => 'left',
						'endpoint' => 0,
					),
					array(
						'key' => 'field_5bb3bbd8d5894',
						'label' => 'Post Types',
						'name' => 'post_types',
						'type' => 'group',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'layout' => 'block',
						'sub_fields' => array(

							array(
								'key' => 'field_5bc0e7785c846',
								'label' => 'Post Types',
								'name' => 'post_type',
								'type' => 'checkbox',
								'instructions' => 'Check the boxes to limit the query to specific post types.',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '50',
									'class' => '',
									'id' => '',
								),
								'choices' => $query_selectable_types,
								'allow_custom' => 0,
								'save_custom' => 0,
								'default_value' => array(
								),
								'layout' => 'vertical',
								'toggle' => 0,
								'return_format' => 'value',
							),

							array(
								'key' => 'field_5bc0e78f5c847',
								'label' => 'Show in Filter',
								'name' => 'filterable',
								'type' => 'true_false',
								'instructions' => 'Allow the items to be filtered by post type.',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '50',
									'class' => '',
									'id' => '',
								),
								'message' => '',
								'default_value' => 0,
								'ui' => 1,
								'ui_on_text' => '',
								'ui_off_text' => '',
							),
						),
					),
					array(
						'key' => 'field_5c5492cd52f78',
						'label' => 'Sort',
						'name' => 'sort',
						'type' => 'group',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'layout' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_5bc0d6cfeeb46',
								'label' => 'Sort By',
								'name' => 'orderby',
								'type' => 'select',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '33',
									'class' => '',
									'id' => '',
								),
								'choices' => array(
									'title' => 'Title',
									'date' => 'Date',
									'menu_order' => 'Wordpress Menu Order',
									'meta_value_num' => 'Custom Field Value (0–9)',
									'meta_value' => 'Custom Field Value (A–Z)',
									'rand' => 'Random',
									'post__in' => 'Selected Post Order'
								),
								'default_value' => false,
								'allow_null' => 1,
								'multiple' => 0,
								'ui' => 0,
								'return_format' => 'value',
								'ajax' => 0,
								'placeholder' => '',
							),
							array(
								'key' => 'field_5bc0d734eeb48',
								'label' => 'Sort Order',
								'name' => 'order',
								'type' => 'select',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '33',
									'class' => '',
									'id' => '',
								),
								'choices' => array(
									'asc' => 'Ascending',
									'desc' => 'Descending',
								),
								'default_value' => false,
								'allow_null' => 0,
								'multiple' => 0,
								'ui' => 0,
								'return_format' => 'value',
								'ajax' => 0,
								'placeholder' => '',
							),
							array(
								'key' => 'field_5c5492e652f79',
								'label' => 'Meta Key',
								'name' => 'meta_key',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => array(
									array(
										array(
											'field' => 'field_5bc0d6cfeeb46',
											'operator' => '==',
											'value' => 'meta_value_num',
										),
									),
									array(
										array(
											'field' => 'field_5bc0d6cfeeb46',
											'operator' => '==',
											'value' => 'meta_value',
										),
									),
								),
								'wrapper' => array(
									'width' => '33',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
						),
					),
					array(
						'key' => 'field_5c54925e52f76',
						'label' => 'Taxonomy Query',
						'name' => '',
						'type' => 'tab',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '33',
							'class' => '',
							'id' => '',
						),
						'placement' => 'top',
						'endpoint' => 0,
					),
					array(
						'key' => 'field_5c548fd28337c',
						'label' => 'Taxonomy Arguments',
						'name' => 'tax_query',
						'type' => 'group',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'layout' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_5bb3bc25d5895',
								'label' => 'Arguments',
								'name' => 'arguments',
								'type' => 'repeater',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'wpml_cf_preferences' => 0,
								'collapsed' => 'field_5c548f0a83377',
								'min' => 0,
								'max' => 0,
								'layout' => 'block',
								'button_label' => 'Add Taxonomy',
								'sub_fields' => array(
									array(
										'key' => 'field_5bc0e96882625',
										'label' => 'Taxonomy',
										'name' => 'taxonomy',
										'type' => 'text',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '50',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'maxlength' => '',
									),
									array(
										'key' => 'field_5c548f0a83377',
										'label' => 'Terms',
										'name' => 'terms',
										'type' => 'text',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '50',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'maxlength' => '',
									),
									array(
										'key' => 'field_5bc0ea4f8262a',
										'label' => 'Show in Filter',
										'name' => 'filterable',
										'type' => 'true_false',
										'instructions' => 'Allow the items to be filtered by this taxonomy.',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '50',
											'class' => '',
											'id' => '',
										),
										'message' => '',
										'default_value' => 0,
										'ui' => 1,
										'ui_on_text' => '',
										'ui_off_text' => '',
									),
									array(
										'key' => 'field_5d7652dabb557',
										'label' => 'Allow multiple selections',
										'name' => 'multiple',
										'type' => 'true_false',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => array(
											array(
												array(
													'field' => 'field_5bc0ea4f8262a',
													'operator' => '==',
													'value' => '1',
												),
											),
										),
										'wrapper' => array(
											'width' => '50',
											'class' => '',
											'id' => '',
										),
										'message' => '',
										'default_value' => 0,
										'ui' => 1,
										'ui_on_text' => '',
										'ui_off_text' => '',
									),
								),
							),
							array(
								'key' => 'field_5c548fdc8337d',
								'label' => 'Relation',
								'name' => 'relation',
								'type' => 'select',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'choices' => array(
									'and' => 'And',
									'or' => 'Or',
								),
								'default_value' => false,
								'allow_null' => 0,
								'multiple' => 0,
								'ui' => 0,
								'return_format' => 'value',
								'ajax' => 0,
								'placeholder' => '',
							),
						),
					),
					array(
						'key' => 'field_5c5492a352f77',
						'label' => 'Meta Query',
						'name' => '',
						'type' => 'tab',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '33',
							'class' => '',
							'id' => '',
						),
						'placement' => 'top',
						'endpoint' => 0,
					),
					array(
						'key' => 'field_5c5490fa83384',
						'label' => 'Meta Query',
						'name' => 'meta_query',
						'type' => 'group',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'layout' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_5c5490fa83385',
								'label' => 'Arguments',
								'name' => 'arguments',
								'type' => 'repeater',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'collapsed' => 'field_5c5490fa83386',
								'min' => 0,
								'max' => 0,
								'layout' => 'block',
								'button_label' => 'Add Key',
								'sub_fields' => array(
									array(
										'key' => 'field_5c5490fa83386',
										'label' => 'Key',
										'name' => 'key',
										'type' => 'text',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '33',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'maxlength' => '',
									),
									array(
										'key' => 'field_5c5490fa83387',
										'label' => 'Value',
										'name' => 'value',
										'type' => 'text',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '33',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'maxlength' => '',
									),
									array(
										'key' => 'field_5c5491298338a',
										'label' => 'Compare',
										'name' => 'compare',
										'type' => 'select',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '33',
											'class' => '',
											'id' => '',
										),
										'choices' => array(
											'=' => '=',
											'!=' => '!=',
											'>' => '>',
											'>=' => '>=',
											'<' => '<',
											'<=' => '<=',
											'LIKE' => 'LIKE',
											'NOT LIKE' => 'NOT LIKE',
											'IN' => 'IN',
											'NOT IN' => 'NOT IN',
											'BETWEEN' => 'BETWEEN',
											'NOT BETWEEN' => 'NOT BETWEEN',
										),
										'default_value' => '=',
										'allow_null' => 0,
										'multiple' => 0,
										'ui' => 0,
										'return_format' => 'value',
										'ajax' => 0,
										'placeholder' => '',
									),
								),
							),
							array(
								'key' => 'field_5c5490fa83389',
								'label' => 'Relation',
								'name' => 'relation',
								'type' => 'select',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'choices' => array(
									'and' => 'And',
									'or' => 'Or',
								),
								'default_value' => false,
								'allow_null' => 0,
								'multiple' => 0,
								'ui' => 0,
								'return_format' => 'value',
								'ajax' => 0,
								'placeholder' => '',
							),
						),
					),
					array(
						'key' => 'field_5e8cc013c97b3',
						'label' => 'Page Parameters',
						'name' => '',
						'type' => 'tab',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'placement' => 'top',
						'endpoint' => 0,
					),
					array(
						'key' => 'field_5e8cc037c97b4',
						'label' => 'Page Parameters',
						'name' => 'page_params',
						'type' => 'group',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'layout' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_5ef4b03454843',
								'label' => 'Depth',
								'name' => 'depth',
								'type' => 'select',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '40',
									'class' => '',
									'id' => '',
								),
								'choices' => array(
									'all' => 'All results',
									'top' => 'Top-level only (no parent)',
									'parent' => 'Filter by parent',
								),
								'default_value' => 'all',
								'allow_null' => 0,
								'multiple' => 0,
								'ui' => 0,
								'return_format' => 'value',
								'ajax' => 0,
								'placeholder' => '',
							),
							array(
								'key' => 'field_5e8cc05bc97b5',
								'label' => 'Parent',
								'name' => 'post_parent',
								'type' => 'post_object',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => array(
									array(
										array(
											'field' => 'field_5ef4b03454843',
											'operator' => '==',
											'value' => 'parent',
										),
									),
								),
								'wrapper' => array(
									'width' => '60',
									'class' => '',
									'id' => '',
								),
								'post_type' => '',
								'taxonomy' => '',
								'allow_null' => 1,
								'multiple' => 0,
								'return_format' => 'id',
								'ui' => 1,
							),
							array(
								'key' => 'field_5e946ca65159f',
								'label' => 'Manually Select Items',
								'name' => 'post__in',
								'type' => 'post_object',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'post_type' => '',
								'taxonomy' => '',
								'allow_null' => 1,
								'multiple' => 1,
								'return_format' => 'id',
								'ui' => 1,
							),
						),
					),
				),
			),
			array(
				'key' => 'field_5bc4cc9a9b051',
				'label' => 'Taxonomy Parameters',
				'name' => 'taxonomy',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5bb3bbb6d5893',
							'operator' => '==',
							'value' => 'terms',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_5c5493ee0665d',
						'label' => 'Taxonomy',
						'name' => 'taxonomy',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
				),
			),
		),
		'active' => false,
	)
);
