<?php

//
// GROUPS
//

$GLOBALS['fw_fields']['builder_groups']['block_content']['heading'] = array(
	'settings' => array(
		'title' => 'Content — Heading'
	),
	'field_group' => array (
		'key' => 'builder_block_content_heading',
		'title' => 'Heading',
		'fields' => array(
			array(
				'key' => 'builder_block_content_heading_text',
				'label' => 'Text',
				'name' => 'text',
				'type' => 'text',
			),
			array(
				'key' => 'builder_block_content_heading_level',
				'label' => 'Heading Level',
				'name' => 'level',
				'type' => 'select',
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'h1' => 'Heading 1',
					'h2' => 'Heading 2',
					'h3' => 'Heading 3',
					'h4' => 'Heading 4',
					'h5' => 'Heading 5',
					'h6' => 'Heading 6',
				),
				'default_value' => 'h2',
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
			),
			array(
				'key' => 'builder_block_content_heading_css',
				'label' => 'Additional CSS Classes',
				'name' => 'classes',
				'type' => 'text',
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
			),
		),
		'active' => false,
	)
);

$GLOBALS['fw_fields']['builder_groups']['block_content']['text'] = array(
	'settings' => array(
		'title' => 'Content — Text'
	),
	'field_group' => array (
		'key' => 'builder_block_content_text',
		'title' => 'Text',
		'fields' => array(
			array(
				'key' => 'builder_block_content_text_body',
				'label' => 'Body',
				'name' => 'body',
				'type' => 'wysiwyg',
				'tabs' => 'all',
				'toolbar' => 'full',
				'media_upload' => 1,
			),
		),
		'active' => false,
	)
);

$GLOBALS['fw_fields']['builder_groups']['block_content']['image'] = array(
	'settings' => array(
		'title' => 'Content — Image'
	),
	'field_group' => array (
		'key' => 'builder_block_content_image',
		'title' => 'Image',
		'fields' => array(
			array(
				'key' => 'builder_block_content_image_file',
				'label' => 'Image',
				'name' => 'image_file',
				'type' => 'image',
				'wrapper' => array(
					'width' => '40',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'id',
				'preview_size' => 'medium',
				'library' => 'all',
			),
			array(
				'key' => 'builder_block_content_image_options',
				'label' => 'Options',
				'name' => 'options',
				'type' => 'group',
				'instructions' => 'Display and functional options for the image. Set the title and caption by editing the attachment directly.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '60',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'builder_block_content_image_options_title',
						'label' => 'Show Title',
						'name' => 'title',
						'type' => 'select',
						'choices' => array(
							'none' => 'No title',
							'above' => 'Above image',
							'below' => 'Below image',
						),
						'default_value' => false,
						'allow_null' => 0,
						'multiple' => 0,
						'return_format' => 'value',
					),
					array(
						'key' => 'builder_block_content_image_options_caption',
						'label' => 'Show Caption',
						'name' => 'caption',
						'type' => 'true_false',
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'default_value' => 0,
						'ui' => 1,
						'ui_on_text' => '',
						'ui_off_text' => '',
					),
					array(
						'key' => 'builder_block_content_image_options_description',
						'label' => 'Show Description',
						'name' => 'description',
						'type' => 'true_false',
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'default_value' => 0,
						'ui' => 1,
						'ui_on_text' => '',
						'ui_off_text' => '',
					),
					array(
						'key' => 'builder_block_content_image_options_link',
						'label' => 'Link',
						'name' => 'link',
						'type' => 'select',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '30',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'none' => 'No link',
							'zoom' => 'Zoom',
							'post' => 'Post / Page',
							'url' => 'URL',
						),
						'default_value' => false,
						'allow_null' => 0,
						'multiple' => 0,
						'ui' => 0,
						'return_format' => 'value',
						'ajax' => 0,
					),
					array(
						'key' => 'builder_block_content_image_options_url',
						'label' => 'URL',
						'name' => 'url',
						'type' => 'url',
						'conditional_logic' => array(
							array(
								array(
									'field' => 'builder_block_content_image_options_link',
									'operator' => '==',
									'value' => 'url',
								),
							),
						),
						'wrapper' => array(
							'width' => '70',
							'class' => '',
							'id' => '',
						),
					),
					array(
						'key' => 'builder_block_content_image_options_post',
						'label' => 'Post',
						'name' => 'post',
						'type' => 'post_object',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'builder_block_content_image_options_link',
									'operator' => '==',
									'value' => 'post',
								),
							),
						),
						'wrapper' => array(
							'width' => '70',
							'class' => '',
							'id' => '',
						),
						'post_type' => '',
						'taxonomy' => '',
						'allow_null' => 0,
						'multiple' => 0,
						'return_format' => 'id',
						'ui' => 1,
					),
					array(
						'key' => 'builder_block_content_image_options_magnify',
						'label' => 'Magnify',
						'name' => 'magnify',
						'type' => 'true_false',
						'message' => 'Magnify image on hover',
						'default_value' => 0,
						'ui' => 1,
						'ui_on_text' => '',
						'ui_off_text' => '',
					),
				),
			),
		),
		'active' => false,
	)
);

$GLOBALS['fw_fields']['builder_groups']['block_content']['video'] = array(
	'settings' => array(
		'title' => 'Content — Video'
	),
	'field_group' => array (
		'key' => 'builder_block_content_video',
		'title' => 'Video',
		'fields' => array(
			array(
				'key' => 'builder_block_content_video_source',
				'label' => 'Video Source',
				'name' => 'source',
				'type' => 'select',
				'choices' => array(
					'upload' => 'Media Library',
					'embed' => 'Embed',
				),
				'default_value' => false,
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
			),
			array(
				'key' => 'builder_block_content_video_url',
				'label' => 'Video URL',
				'name' => 'url',
				'type' => 'url',
				'conditional_logic' => array(
					array(
						array(
							'field' => 'builder_block_content_video_source',
							'operator' => '==',
							'value' => 'embed',
						),
					),
				),
			),
			array(
				'key' => 'builder_block_content_video_files',
				'label' => 'Files',
				'name' => 'files',
				'type' => 'repeater',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'builder_block_content_video_source',
							'operator' => '==',
							'value' => 'upload',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => '',
				'min' => 0,
				'max' => 0,
				'layout' => 'block',
				'button_label' => 'Add File',
				'sub_fields' => array(
					array(
						'key' => 'builder_block_content_video_files_file',
						'label' => 'File',
						'name' => 'file',
						'type' => 'file',
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'return_format' => 'id',
						'library' => 'all',
					),
					array(
						'key' => 'builder_block_content_video_files_type',
						'label' => 'Type',
						'name' => 'type',
						'type' => 'select',
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'mp4' => 'MP4',
							'webm' => 'WebM',
							'ogg' => 'Ogg',
						),
						'default_value' => false,
						'allow_null' => 0,
						'multiple' => 0,
						'ui' => 0,
						'return_format' => 'value',
						'ajax' => 0,
					),
				),
			),
			array(
				'key' => 'builder_block_content_video_files_atts',
				'label' => 'Attributes',
				'name' => 'attributes',
				'type' => 'checkbox',
				'conditional_logic' => array(
					array(
						array(
							'field' => 'builder_block_content_video_source',
							'operator' => '==',
							'value' => 'upload',
						),
					),
				),
				'choices' => array(
					'loop' => 'Loop',
					'autoplay' => 'Autoplay',
					'muted' => 'Muted',
					'controls' => 'Show Controls',
				),
				'allow_custom' => 0,
				'default_value' => array(
				),
				'layout' => 'horizontal',
				'toggle' => 0,
				'return_format' => 'value',
				'save_custom' => 0,
			),
		),
		'active' => false,
	)
);

$GLOBALS['fw_fields']['builder_groups']['block_content']['animation'] = array(
	'settings' => array(
		'title' => 'Content — Animation'
	),
	'field_group' => array (
		'key' => 'builder_block_content_animation',
		'title' => 'Animation',
		'fields' => array(
			array(
				'key' => 'builder_block_content_animation_file',
				'label' => 'File',
				'name' => 'file',
				'type' => 'file',
				'return_format' => 'id',
				'library' => 'all',
				'mime_types' => 'json',
			),
			array(
				'key' => 'builder_block_content_animation_display',
				'label' => 'Display',
				'name' => '',
				'type' => 'accordion',
			),
			array(
				'key' => 'builder_block_content_animation_loop',
				'label' => 'Loop',
				'name' => 'loop',
				'type' => 'true_false',
				'wrapper' => array(
					'width' => '33',
					'class' => '',
					'id' => '',
				),
				'message' => 'Loop playback',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'builder_block_content_animation_inview',
				'label' => 'In View',
				'name' => 'in_view',
				'type' => 'true_false',
				'wrapper' => array(
					'width' => '33',
					'class' => '',
					'id' => '',
				),
				'message' => 'Start / stop when in view',
				'default_value' => 1,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'builder_block_content_animation_rewind',
				'label' => 'Rewind on stop',
				'name' => 'rewind',
				'type' => 'true_false',
				'conditional_logic' => array(
					array(
						array(
							'field' => 'builder_block_content_animation_inview',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '33',
					'class' => '',
					'id' => '',
				),
				'message' => 'Rewind to first frame when stopped',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
		),
		'active' => false,
	)
);

$GLOBALS['fw_fields']['builder_groups']['block_content']['accordion'] = array(
	'settings' => array(
		'title' => 'Content — Accordion'
	),
	'field_group' => array (
		'key' => 'builder_block_content_accordion',
		'title' => 'Accordion',
		'fields' => array(
			array(
				'key' => 'builder_block_content_accordion_repeater',
				'label' => 'Content',
				'name' => 'accordion',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => '',
				'min' => 0,
				'max' => 0,
				'layout' => 'block',
				'button_label' => 'Add Content',
				'sub_fields' => array(
					array(
						'key' => 'builder_block_content_accordion_repeater_heading',
						'label' => 'Heading',
						'name' => 'heading',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'builder_block_content_accordion_repeater_content',
						'label' => 'Content',
						'name' => 'content',
						'type' => 'wysiwyg',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'tabs' => 'all',
						'toolbar' => 'full',
						'media_upload' => 0,
						'delay' => 0,
					),
				),
			),
			array(
				'key' => 'builder_block_content_accordion_repeater_classes',
				'label' => 'Classes',
				'name' => 'accordion_classes',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_60d4c3c5c2c67',
						'label' => 'Element',
						'name' => 'element',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_60d4c417c2c69',
						'label' => 'Card',
						'name' => 'card',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_60d4c3d1c2c68',
						'label' => 'Heading',
						'name' => 'heading',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_60d4c41bc2c6a',
						'label' => 'Content',
						'name' => 'content',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
				),
			),
		),
		'active' => false,
	)
);

$GLOBALS['fw_fields']['builder_groups']['block_content']['query'] = array(
	'settings' => array(
		'title' => 'Content — Query Object'
	),
	'field_group' => array (
		'key' => 'builder_block_content_query',
		'title' => 'Query Object',
		'fields' => array(
			array(
				'key' => 'builder_block_content_query_settings',
				'label' => 'Query Settings',
				'name' => '',
				'type' => 'accordion',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'open' => 0,
				'multi_expand' => 0,
				'endpoint' => 0,
			),
			array(
				'key' => 'builder_block_content_query_query',
				'label' => 'Query',
				'name' => 'query',
				'type' => 'clone',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'clone' => array(
					0 => 'builder_function_query',
				),
				'display' => 'seamless',
				'layout' => 'block',
				'prefix_label' => 0,
				'prefix_name' => 0,
			),
			array(
				'key' => 'builder_block_content_query_accordion_display',
				'label' => 'Display Settings',
				'name' => '',
				'type' => 'accordion',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'open' => 0,
				'multi_expand' => 0,
				'endpoint' => 0,
			),
			array(
				'key' => 'builder_block_content_query_template',
				'label' => 'Item Template',
				'name' => 'template',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '[post type]-card',
				'prepend' => 'previews/',
				'append' => '.php',
				'maxlength' => '',
			),
			array(
				'key' => 'builder_block_content_query_display',
				'label' => 'Display',
				'name' => 'display',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'grid' => 'Grid',
					'carousel' => 'Carousel',
					'list' => 'List',
				),
				'default_value' => 'grid',
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'builder_block_content_query_carousel',
				'label' => 'Carousel Settings',
				'name' => 'swiper',
				'type' => 'clone',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'builder_block_content_query_display',
							'operator' => '==',
							'value' => 'carousel',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'clone' => array(
					0 => 'builder_setting_carousel',
				),
				'display' => 'group',
				'layout' => 'block',
				'prefix_label' => 0,
				'prefix_name' => 0,
			),
			array(
				'key' => 'builder_block_content_query_grid',
				'label' => 'Grid Settings',
				'name' => 'grid',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'builder_block_content_query_display',
							'operator' => '==',
							'value' => 'grid',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'builder_block_content_query_grid_masonry',
						'label' => 'Use Masonry',
						'name' => 'masonry',
						'type' => 'true_false',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'message' => '',
						'default_value' => 0,
						'ui' => 0,
						'ui_on_text' => '',
						'ui_off_text' => '',
					),
				),
			),
			array(
				'key' => 'builder_block_content_query_accordion_builder',
				'label' => 'Builder',
				'name' => '',
				'type' => 'accordion',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'open' => 0,
				'multi_expand' => 0,
				'endpoint' => 0,
			),
			array(
				'key' => 'builder_block_content_query_objectclasses',
				'label' => 'Object Classes',
				'name' => 'object_classes',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'builder_block_content_query_containers',
				'label' => 'Containers',
				'name' => 'containers',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => '',
				'min' => 0,
				'max' => 0,
				'layout' => 'block',
				'button_label' => 'Add Container',
				'sub_fields' => array(
					array(
						'key' => 'builder_block_content_query_containers_classes',
						'label' => 'Container Classes',
						'name' => 'container_classes',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'builder_block_content_query_elements',
						'label' => 'Elements',
						'name' => 'elements',
						'type' => 'flexible_content',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'layouts' => array(
							'builder_block_content_query_elements_items' => array(
								'key' => 'builder_block_content_query_elements_items',
								'name' => 'query_items',
								'label' => 'Query Items',
								'display' => 'block',
								'sub_fields' => array(
									array(
										'key' => 'builder_block_content_query_elements_items_classes',
										'label' => 'Classes',
										'name' => 'classes',
										'type' => 'group',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'layout' => 'block',
										'sub_fields' => array(
											array(
												'key' => 'field_5f7b45468ed80',
												'label' => 'Element',
												'name' => 'element',
												'type' => 'text',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => 0,
												'wrapper' => array(
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'maxlength' => '',
											),
											array(
												'key' => 'field_5f7b45528ed81',
												'label' => 'Item',
												'name' => 'item',
												'type' => 'text',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => 0,
												'wrapper' => array(
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'maxlength' => '',
											),
											array(
												'key' => 'field_5f7b4d441a2ba',
												'label' => 'Carousel Controls',
												'name' => 'controls',
												'type' => 'text',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => array(
													array(
														array(
															'field' => 'builder_block_content_query_display',
															'operator' => '==',
															'value' => 'carousel',
														),
													),
												),
												'wrapper' => array(
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'maxlength' => '',
											),
										),
									),
								),
								'min' => '0',
								'max' => '1',
							),
							'layout_5f77357b7c883' => array(
								'key' => 'layout_5f77357b7c883',
								'name' => 'filter_items',
								'label' => 'Filter Items',
								'display' => 'block',
								'sub_fields' => array(
									array(
										'key' => 'field_5f7736617c886',
										'label' => 'Classes',
										'name' => 'classes',
										'type' => 'group',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'layout' => 'block',
										'sub_fields' => array(
											array(
												'key' => 'field_5f777991bd5e6',
												'label' => 'Element',
												'name' => 'element',
												'type' => 'text',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => 0,
												'wrapper' => array(
													'width' => '33',
													'class' => '',
													'id' => '',
												),
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'maxlength' => '',
											),
											array(
												'key' => 'field_5f777997bd5e7',
												'label' => 'Headings',
												'name' => 'headings',
												'type' => 'text',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => 0,
												'wrapper' => array(
													'width' => '33',
													'class' => '',
													'id' => '',
												),
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'maxlength' => '',
											),
											array(
												'key' => 'field_5f7779b3bd5e8',
												'label' => 'Lists',
												'name' => 'lists',
												'type' => 'text',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => 0,
												'wrapper' => array(
													'width' => '33',
													'class' => '',
													'id' => '',
												),
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'maxlength' => '',
											),
										),
									),
									array(
										'key' => 'field_5f7775b035532',
										'label' => 'Filter Settings',
										'name' => '',
										'type' => 'accordion',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'open' => 0,
										'multi_expand' => 0,
										'endpoint' => 0,
									),
									array(
										'key' => 'field_5f7775e135534',
										'label' => 'Use Accordions',
										'name' => 'accordions',
										'type' => 'true_false',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '50',
											'class' => '',
											'id' => '',
										),
										'message' => '',
										'default_value' => 0,
										'ui' => 0,
										'ui_on_text' => '',
										'ui_off_text' => '',
									),
								),
								'min' => '',
								'max' => '1',
							),
							'layout_5f870c156d967' => array(
								'key' => 'layout_5f870c156d967',
								'name' => 'sort',
								'label' => 'Sort Items',
								'display' => 'block',
								'sub_fields' => array(
									array(
										'key' => 'field_5f8710f732c55',
										'label' => 'Classes',
										'name' => 'classes',
										'type' => 'group',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'layout' => 'block',
										'sub_fields' => array(
											array(
												'key' => 'field_5f8710f732c56',
												'label' => 'Element',
												'name' => 'element',
												'type' => 'text',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => 0,
												'wrapper' => array(
													'width' => '33',
													'class' => '',
													'id' => '',
												),
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'maxlength' => '',
											),
											array(
												'key' => 'field_5f8710f732c57',
												'label' => 'Headings',
												'name' => 'headings',
												'type' => 'text',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => 0,
												'wrapper' => array(
													'width' => '33',
													'class' => '',
													'id' => '',
												),
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'maxlength' => '',
											),
											array(
												'key' => 'field_5f8710f732c58',
												'label' => 'Lists',
												'name' => 'lists',
												'type' => 'text',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => 0,
												'wrapper' => array(
													'width' => '33',
													'class' => '',
													'id' => '',
												),
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'maxlength' => '',
											),
										),
									),
									array(
										'key' => 'field_5f870c396d968',
										'label' => 'Sort Options',
										'name' => 'options',
										'type' => 'checkbox',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'choices' => array(
											'date_desc' => 'Date (Newest First)',
											'date_asc' => 'Date (Oldest First)',
											'title_asc' => 'Title (Ascending)',
											'title_desc' => 'Title (Descending)',
										),
										'allow_custom' => 0,
										'default_value' => array(
										),
										'layout' => 'horizontal',
										'toggle' => 0,
										'return_format' => 'array',
										'save_custom' => 0,
									),
								),
								'min' => '',
								'max' => '1',
							),
							'layout_5f77354a7c880' => array(
								'key' => 'layout_5f77354a7c880',
								'name' => 'search',
								'label' => 'Search Field',
								'display' => 'block',
								'sub_fields' => array(
									array(
										'key' => 'field_5f7736787c887',
										'label' => 'Classes',
										'name' => 'classes',
										'type' => 'text',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'maxlength' => '',
									),
									array(
										'key' => 'field_5f777657588ba',
										'label' => 'Placeholder',
										'name' => 'placeholder',
										'type' => 'text',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'maxlength' => '',
									),
								),
								'min' => '',
								'max' => '1',
							),
							'layout_5f77355b7c881' => array(
								'key' => 'layout_5f77355b7c881',
								'name' => 'post_count',
								'label' => 'Post Count',
								'display' => 'block',
								'sub_fields' => array(
									array(
										'key' => 'field_5f77367f7c888',
										'label' => 'Classes',
										'name' => 'classes',
										'type' => 'text',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'maxlength' => '',
									),
								),
								'min' => '',
								'max' => '',
							),
							'layout_635029858b988' => array(
								'key' => 'layout_635029858b988',
								'name' => 'text',
								'label' => 'Text',
								'display' => 'block',
								'sub_fields' => array(
									array(
										'key' => 'field_63502986c732a',
										'label' => 'Text',
										'name' => 'text',
										'type' => 'wysiwyg',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'delay' => 0,
										'tabs' => 'all',
										'toolbar' => 'full',
										'media_upload' => 0,
									),
								),
								'min' => '',
								'max' => '',
							),
							'layout_5f7737577c88b' => array(
								'key' => 'layout_5f7737577c88b',
								'name' => 'pagination',
								'label' => 'Pagination',
								'display' => 'block',
								'sub_fields' => array(
									array(
										'key' => 'field_5f777313a7680',
										'label' => 'Classes',
										'name' => 'classes',
										'type' => 'text',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'maxlength' => '',
									),
									array(
										'key' => 'field_5f7737627c88c',
										'label' => 'History',
										'name' => 'history',
										'type' => 'true_false',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'message' => '',
										'default_value' => 0,
										'ui' => 0,
										'ui_on_text' => '',
										'ui_off_text' => '',
									),
									array(
										'key' => 'field_5f7f0fd9cc8a8',
										'label' => 'Type',
										'name' => 'type',
										'type' => 'radio',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => array(
											array(
												array(
													'field' => 'builder_block_content_query_display',
													'operator' => '!=',
													'value' => 'carousel',
												),
											),
										),
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'choices' => array(
											'append' => 'Append new items',
											'replace' => 'Replace items',
										),
										'allow_null' => 0,
										'other_choice' => 0,
										'default_value' => 'append',
										'layout' => 'vertical',
										'return_format' => 'value',
										'save_other_choice' => 0,
									),
								),
								'min' => '',
								'max' => '',
							),
						),
						'button_label' => 'Add Element',
						'min' => '',
						'max' => '',
					),
				),
			),
		),
		'active' => false,
	)
);

$GLOBALS['fw_fields']['builder_groups']['block_content']['terms'] = array(
	'settings' => array(
		'title' => 'Content — Post Meta'
	),
	'field_group' => array (
		'key' => 'builder_block_content_terms',
		'title' => 'Post Meta',
		'fields' => array(
			array(
				'key' => 'field_5d77b10b5ecfc',
				'label' => 'Terms',
				'name' => 'terms',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => 'field_5d77b14d5ecfd',
				'min' => 0,
				'max' => 0,
				'layout' => 'block',
				'button_label' => 'Add Term List',
				'sub_fields' => array(
					array(
						'key' => 'field_5d77b14d5ecfd',
						'label' => 'Type',
						'name' => 'type',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '33',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'taxonomy' => 'Taxonomy Terms',
							'meta' => 'Custom Field Value',
						),
						'default_value' => false,
						'allow_null' => 0,
						'multiple' => 0,
						'ui' => 0,
						'return_format' => 'value',
						'ajax' => 0,
						'placeholder' => '',
					),
					array(
						'key' => 'field_5d77ab8a8fffc',
						'label' => 'Taxonomy',
						'name' => 'taxonomy_list',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_5d77b14d5ecfd',
									'operator' => '==',
									'value' => 'taxonomy',
								),
							),
						),
						'wrapper' => array(
							'width' => '66',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'category' => 'Categories',
							'post_tag' => 'Tags',
							'role' => 'Role',
							'research-area' => 'Research Area',
						),
						'default_value' => false,
						'allow_null' => 0,
						'multiple' => 0,
						'ui' => 0,
						'return_format' => 'value',
						'ajax' => 0,
						'placeholder' => '',
					),
					array(
						'key' => 'field_5d77b1835ecfe',
						'label' => 'Field Key',
						'name' => 'field',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_5d77b14d5ecfd',
									'operator' => '==',
									'value' => 'meta',
								),
							),
						),
						'wrapper' => array(
							'width' => '66',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
				),
			),
		),
		'active' => false,
	)
);

$GLOBALS['fw_fields']['builder_groups']['block_content']['template'] = array(
	'settings' => array(
		'title' => 'Content — Template Part'
	),
	'field_group' => array (
		'key' => 'builder_block_content_template',
		'title' => 'Template Part',
		'fields' => array(
			array(
				'key' => 'field_5d7b9bf0e54a3',
				'label' => 'Filename',
				'name' => 'filename',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '[child theme]/template/',
				'append' => '.php',
				'maxlength' => '',
			),
		),
		'active' => false,
	)
);

$GLOBALS['fw_fields']['builder_groups']['block_content']['field'] = array(
	'settings' => array(
		'title' => 'Content — Field Value'
	),
	'field_group' => array (
		'key' => 'builder_block_content_field',
		'title' => 'Field Value',
		'fields' => array(
			array(
				'key' => 'builder_block_content_field_key',
				'label' => 'Field Key',
				'name' => 'field',
				'type' => 'text',
			),
			array(
				'key' => 'builder_block_content_field_id',
				'label' => 'Post ID',
				'name' => 'post_id',
				'type' => 'text',
			),
			array(
				'key' => 'builder_block_content_field_display',
				'label' => 'Display as',
				'name' => 'display',
				'type' => 'select',
				'choices' => array(
					'block' => 'Block',
					'p' => 'Paragraph',
					'h1' => 'Heading 1',
					'h2' => 'Heading 2',
					'h3' => 'Heading 3',
					'h4' => 'Heading 4',
					'h5' => 'Heading 5',
					'h6' => 'Heading 6',
				),
				'default_value' => 'p',
				'allow_null' => 0,
				'multiple' => 0,
				'return_format' => 'value',
			),
			array(
				'key' => 'builder_block_content_field_template',
				'label' => 'Template',
				'name' => 'template',
				'type' => 'text',
				'conditional_logic' => array(
					array(
						array(
							'field' => 'builder_block_content_field_display',
							'operator' => '==',
							'value' => 'block',
						),
					),
				),
				'prepend' => 'blocks/',
				'append' => '.php',
			),
		),
		'active' => false,
	)
);
