<?php

//
// PAGE BUILDER
//

$GLOBALS['fw_fields']['builder'] = array(
	'key' => 'fw_page_builder',
	'title' => 'Page Builder',
	'fields' => array(
		array(
			'key' => 'builder_elements',
			'label' => 'Elements',
			'name' => 'elements',
			'type' => 'flexible_content',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => 'page-builder-field',
				'id' => '',
			),
			'layouts' => array(
				'builder_layout_section' => array(
					'key' => 'builder_layout_section',
					'name' => 'section',
					'label' => 'Section',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'builder_layout_section_id',
							'label' => 'Section ID',
							'name' => 'section_id',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '33',
								'class' => 'page-builder-layout-head head-level-1',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '#',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'builder_layout_section_css',
							'label' => 'Additional CSS Classes',
							'name' => 'classes',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '67',
								'class' => 'page-builder-layout-head head-level-1',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'builder_layout_section_settingsaccordion',
							'label' => 'Section Settings',
							'name' => '',
							'type' => 'accordion',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => 'section-settings-accordion',
								'id' => '',
							),
							'open' => 0,
							'multi_expand' => 0,
							'endpoint' => 0,
						),
						array(
							'key' => 'builder_layout_section_settings',
							'label' => 'Settings',
							'name' => 'settings',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array(
								0 => 'builder_settings',
							),
							'display' => 'seamless',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				'builder_layout_container' => array(
					'key' => 'builder_layout_container',
					'name' => 'container',
					'label' => 'Container',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'builder_layout_container_id',
							'label' => 'Container ID',
							'name' => 'container_id',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '33',
								'class' => 'page-builder-layout-head head-level-2',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '#',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'builder_layout_container_css',
							'label' => 'Additional CSS Classes',
							'name' => 'classes',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '67',
								'class' => 'page-builder-layout-head head-level-2',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'builder_layout_container_settingsaccordion',
							'label' => 'Container Settings',
							'name' => '',
							'type' => 'accordion',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => 'container-settings-accordion',
								'id' => '',
							),
							'open' => 0,
							'multi_expand' => 0,
							'endpoint' => 0,
						),
						array(
							'key' => 'builder_layout_container_width',
							'label' => 'Width',
							'name' => 'width',
							'type' => 'button_group',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '33',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'full' => 'Full',
								1200 => 'Fixed',
							),
							'allow_null' => 0,
							'default_value' => '',
							'layout' => 'horizontal',
							'return_format' => 'value',
						),
						array(
							'key' => 'builder_layout_container_rowclass',
							'label' => 'Row Classes',
							'name' => 'row_classes',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '67',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'builder_layout_container_settings',
							'label' => 'Settings',
							'name' => 'settings',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array(
								0 => 'builder_settings',
							),
							'display' => 'seamless',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				'builder_layout_column' => array(
					'key' => 'builder_layout_column',
					'name' => 'column',
					'label' => 'Column',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'builder_layout_column_id',
							'label' => 'Column ID',
							'name' => 'column_id',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '33',
								'class' => 'page-builder-layout-head head-level-3',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '#',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'builder_layout_column_css',
							'label' => 'Additional CSS Classes',
							'name' => 'classes',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '67',
								'class' => 'page-builder-layout-head head-level-3',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'builder_layout_column_settingsaccordion',
							'label' => 'Column Settings',
							'name' => '',
							'type' => 'accordion',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => 'column-settings-accordion',
								'id' => '',
							),
							'open' => 0,
							'multi_expand' => 0,
							'endpoint' => 0,
						),
						array(
							'key' => 'builder_layout_column_settings',
							'label' => 'Settings',
							'name' => 'settings',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array(
								0 => 'builder_settings',
							),
							'display' => 'seamless',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
						),
						array(
							'key' => 'builder_layout_column_breakpointsaccordion',
							'label' => 'Breakpoints',
							'name' => '',
							'type' => 'accordion',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => 'column-breakpoints-accordion',
								'id' => '',
							),
							'open' => 0,
							'multi_expand' => 0,
							'endpoint' => 0,
						),
						array(
							'key' => 'builder_layout_column_breakpoints',
							'label' => 'Breakpoints',
							'name' => 'breakpoints',
							'type' => 'clone',
							'clone' => array(
								0 => 'builder_function_breakpoints',
							),
							'display' => 'seamless',
							'layout' => 'block',
						),
					),
				),
				'builder_layout_template' => array(
					'key' => 'builder_layout_template',
					'name' => 'template',
					'label' => 'Template',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'builder_layout_template_post',
							'label' => 'Template',
							'name' => 'template',
							'type' => 'post_object',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '75',
								'class' => '',
								'id' => '',
							),
							'post_type' => array(
								0 => 'template',
							),
							'taxonomy' => '',
							'allow_null' => 0,
							'multiple' => 0,
							'return_format' => 'id',
							'ui' => 1,
						),
						array(
							'key' => 'builder_layout_template_resolve',
							'label' => 'Resolve elements',
							'name' => 'resolve',
							'type' => 'true_false',
							'instructions' => 'Close current elements before including this file',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '25',
								'class' => '',
								'id' => '',
							),
							'message' => '',
							'default_value' => 1,
							'ui' => 0,
							'ui_on_text' => '',
							'ui_off_text' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				'builder_layout_include' => array(
					'key' => 'builder_layout_include',
					'name' => 'include',
					'label' => 'File Include',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'builder_layout_include_filename',
							'label' => 'Filename',
							'name' => 'filename',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '75',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '[child theme]/template/',
							'append' => '.php',
							'maxlength' => '',
						),
						array(
							'key' => 'builder_layout_include_resolve',
							'label' => 'Resolve elements',
							'name' => 'resolve',
							'type' => 'true_false',
							'instructions' => 'Close current elements before including this file',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '25',
								'class' => '',
								'id' => '',
							),
							'message' => '',
							'default_value' => 0,
							'ui' => 0,
							'ui_on_text' => '',
							'ui_off_text' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
			),
			'button_label' => 'Add Element',
			'min' => '',
			'max' => '',
			'mc_acf_ft_true_false' => 1,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
		),
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'template',
			),
		),
	),
	'menu_order' => 6,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array(
		0 => 'the_content',
	),
	'active' => true,
	'description' => '',
);


// 2. filter
$GLOBALS['fw_fields']['builder'] = apply_filters ( 'custom_builder', $GLOBALS['fw_fields']['builder'] );

//
// POPULATE LAYOUTS
// builder_flex -> builder
//

foreach ( $GLOBALS['fw_fields']['builder_flex'] as $key => $layout ) {

	// echo '<h4>setting up ' . $key . '</h4>';

	$GLOBALS['fw_fields']['builder']['fields'][0]['layouts']['builder_layout_' . $key] = array (
		'key' => 'builder_layout_' . $key,
		'name' => $key,
		'label' => $layout['title'],
		'display' => 'block',
		'sub_fields' => array(
			array(
				'key' => 'builder_layout_' . $key . '_blockid',
				'label' => 'Block ID',
				'name' => 'block_id',
				'type' => 'text',
				'wrapper' => array(
					'width' => '33',
					'class' => 'page-builder-layout-head head-level-4',
					'id' => '',
				),
				'prepend' => '#',
			),
			array(
				'key' => 'builder_layout_' . $key . '_css',
				'label' => 'Additional CSS Classes',
				'name' => 'classes',
				'type' => 'text',
				'wrapper' => array(
					'width' => '67',
					'class' => 'page-builder-layout-head head-level-4',
					'id' => '',
				),
			),
			array(
				'key' => 'builder_layout_' . $key . '_clone',
				'label' => 'Blocks',
				'name' => 'blocks',
				'type' => 'clone',
				'clone' => array(
					0 => 'builder_' . $key // eg. builder_block_content
				),
				'display' => 'seamless',
				'layout' => 'block',
			),
			array(
				'key' => 'builder_layout_' . $key . '_settingsaccordion',
				'label' => 'Block Settings',
				'name' => '',
				'type' => 'accordion',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => 'block-settings-accordion',
					'id' => '',
				),
				'open' => 0,
				'multi_expand' => 0,
				'endpoint' => 0,
			),
			array(
				'key' => 'builder_layout_' . $key . '_settings',
				'label' => 'Settings',
				'name' => 'settings',
				'type' => 'clone',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'clone' => array(
					0 => 'builder_settings',
				),
				'display' => 'seamless',
				'layout' => 'block',
				'prefix_label' => 0,
				'prefix_name' => 0,
			),
		),
	);

}
